In [1]:
import pandas as pd

# Initial analysis

In [17]:
UNNEEDED_COLUMNS = []

In [27]:
df = pd.read_csv('ticagrelorum.csv', header=0, index_col=0).reset_index(drop=True)

In [19]:
def is_empty(col):
    return all(df[col].isna()) or all(df[col] == ' ')
EMPTY_COLUMNS = [col for col in df.columns if is_empty(col)]
EMPTY_COLUMNS

/Users/alexandershein/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

['Cortisol', 'Beta_h_cort', 'Ratio_Cort']

In [20]:
SINGLE_VALUE_COLUMNS = [col for col in df.columns if len(df[col].unique()) == 1]
SINGLE_VALUE_COLUMNS

['КШ', 'Энд_пер_арт', 'miR_142', 'Cortisol', 'Beta_h_cort', 'Ratio_Cort']

In [21]:
df = df.drop([*UNNEEDED_COLUMNS, *SINGLE_VALUE_COLUMNS, *EMPTY_COLUMNS], axis=1)

In [3]:
df

,ID_порядковый,Пол,Возраст,Рост,Вес,ИМТ,Курение,Гиперлипидемия,СД,АГ,...,Конц_мет_AR_Кат,miR_142,miR_126,miR_150,miR_223,miR_29a_3p,miR_34a,Cortisol,Beta_h_cort,Ratio_Cort
ID,,,,,,,,,,,,,,,,,,,,,
1,1,1,50,175,98,32.0,0,0,0,1,...,1,-88,-88.00,-88.00,-88.00,-88.00,-88.00,,,
2,2,2,78,-88,-88,-88.0,0,0,0,1,...,1,-88,-88.00,-88.00,-88.00,-88.00,-88.00,,,
3,3,1,58,-88,-88,-88.0,0,1,0,1,...,1,-88,-88.00,-88.00,-88.00,-88.00,-88.00,,,
4,4,1,56,176,90,-88.0,0,0,0,1,...,1,-88,-88.00,-88.00,-88.00,-88.00,-88.00,,,
5,5,1,47,-88,-88,-88.0,1,0,0,1,...,1,-88,-88.00,-88.00,-88.00,-88.00,-88.00,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,124,1,68,-88,-88,-88.0,0,0,0,1,...,1,-88,31.33,27.74,26.82,32.70,32.21,,,
56,125,1,58,-88,-88,-88.0,0,0,0,1,...,2,-88,31.92,26.64,28.29,33.04,33.19,,,
60,126,1,37,-88,-88,-88.0,1,1,0,0,...,2,-88,26.53,28.06,23.34,29.07,29.59,,,
62,127,1,59,-88,-88,-88.0,1,0,0,1,...,2,-88,29.67,27.54,26.22,32.34,30.41,,,
63,128,1,59,-88,-88,-88.0,0,1,0,1,...,2,-88,28.33,27.82,24.22,31.12,30.11,,,

In [6]:
df.head()

,ID_порядковый,Пол,Возраст,Рост,Вес,ИМТ,Курение,Гиперлипидемия,СД,АГ,...,Конц_мет_AR_Кат,miR_142,miR_126,miR_150,miR_223,miR_29a_3p,miR_34a,Cortisol,Beta_h_cort,Ratio_Cort
ID,,,,,,,,,,,,,,,,,,,,,
1,1,1,50,175,98,32.0,0,0,0,1,...,1,-88,-88.0,-88.0,-88.0,-88.0,-88.0,,,
2,2,2,78,-88,-88,-88.0,0,0,0,1,...,1,-88,-88.0,-88.0,-88.0,-88.0,-88.0,,,
3,3,1,58,-88,-88,-88.0,0,1,0,1,...,1,-88,-88.0,-88.0,-88.0,-88.0,-88.0,,,
4,4,1,56,176,90,-88.0,0,0,0,1,...,1,-88,-88.0,-88.0,-88.0,-88.0,-88.0,,,
5,5,1,47,-88,-88,-88.0,1,0,0,1,...,1,-88,-88.0,-88.0,-88.0,-88.0,-88.0,,,

In [22]:
df.columns

Index(['ID_порядковый', 'Пол', 'Возраст', 'Рост', 'Вес', 'ИМТ', 'Курение',
       'Гиперлипидемия', 'СД', 'АГ', 'ИИ', 'ПН', 'Hb', 'ИМ_Ан', 'Тромб_ст',
       'ПерА', 'Аритмия', 'ХСН', 'Рестеноз', 'ЧКВ', 'ФВЛЖ', 'САД', 'ДАД',
       'ЧСС', 'Аневризма', 'Лейк', 'Тромб', 'Холест_общ', 'ЛПНП',
       'Триглицериды', 'Креатинин', 'Глюкоза', 'Гематокрит', 'Кол_сос',
       'Ствол_ЛКА', 'ОА', 'ВТК', 'ПКА', 'ДВ', 'АТК', 'ПНА_ПМЖВ',
       'Покрытие_стента', 'Диаметр_стента', 'Длина_стент_сум', 'Кол_стент',
       'АСК', 'БКК', 'Диурет', 'ИПП', 'Статины', 'БАБ', 'иАПФ', 'Инг_РА',
       'Диагноз', 'PRU', 'PRU_base', 'Ing', 'CYP2C19_2', 'CYP2C19_17',
       'ABCB1_3435', 'SLCO1B1', 'CYP3A5', 'CYP3A4_22', 'CYP3A4_rs2242480',
       'CES1', 'UGT2B7', 'PON1', 'PEAR1_rs822442', 'PEAR1_rs5918', 'IGTB3',
       'P2Y12', 'Тика_конц', 'Конц_мет_AR', 'Отн_M_T', 'Конц_Тика_Кат',
       'Конц_мет_AR_Кат', 'miR_126', 'miR_150', 'miR_223', 'miR_29a_3p',
       'miR_34a'],
      dtype='object')

In [33]:
df['Рестеноз'].unique()

array([0, 4, 1])

# Regression models